export const USER_PROVIDERS = {
  EMAIL: 'email',
  GOOGLE: 'google',
  GOOGLE_WITH_PASSWORD: 'google_with_password',
  DEVELOPMENT: 'development',
  FAKE: 'fake',
  LOCAL: 'local'
} as const;

export const TOKEN_TYPES = {
  AUTH: 'auth',
  EMAIL_CONFIRMATION: 'email_confirmation',
  PASSWORD_RESET: 'password_reset',
  ACCOUNT_DELETION: 'account_deletion',
  ACCOUNT_DELETION_CONFIRMATION: 'account_deletion_confirmation',
  ACCOUNT_DELETION_REQUEST: 'account_deletion_request'
} as const;

export const AUTH_ACTIONS = {
  EMAIL_CONFIRMED: 'email_confirmed',
  AUTH_TOKEN: 'auth_token',
  PASSWORD_RESET_READY: 'password_reset_ready',
  EMAIL_ALREADY_VERIFIED: 'email_already_verified',
  ACCOUNT_DELETED: 'account_deleted'
} as const;

export const ACCOUNT_STATUS = {
  ACTIVE: 'active',
  SUSPENDED: 'suspended',
  DELETED: 'deleted',
  PENDING_VERIFICATION: 'pending_verification'
} as const;

export const ERROR_CODES = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  MISSING_TOKEN: 'MISSING_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_INACTIVE: 'USER_INACTIVE',
  EMAIL_REQUIRED: 'EMAIL_REQUIRED',
  INVALID_EMAIL: 'INVALID_EMAIL',
  PASSWORD_REQUIRED: 'PASSWORD_REQUIRED',
  WEAK_PASSWORD: 'WEAK_PASSWORD',
  NAME_REQUIRED: 'NAME_REQUIRED',
  INVALID_DATE: 'INVALID_DATE',
  OAUTH_NOT_CONFIGURED: 'OAUTH_NOT_CONFIGURED',
  OAUTH_FAILED: 'OAUTH_FAILED',
  OAUTH_ERROR: 'OAUTH_ERROR',
  MISSING_RESET_DATA: 'MISSING_RESET_DATA',
  RESET_TOKEN_EXPIRED: 'RESET_TOKEN_EXPIRED',
  INVALID_RESET_TOKEN: 'INVALID_RESET_TOKEN',
  MISSING_DELETION_TOKEN: 'MISSING_DELETION_TOKEN',
  INVALID_DELETION_TOKEN: 'INVALID_DELETION_TOKEN',
  EMAIL_SEND_FAILED: 'EMAIL_SEND_FAILED',
  EMAIL_SERVICE_UNAVAILABLE: 'EMAIL_SERVICE_UNAVAILABLE',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  ACCESS_DENIED: 'ACCESS_DENIED',
  FORBIDDEN: 'FORBIDDEN'
} as const;

export const VALIDATION_RULES = {
  PASSWORD_MIN_LENGTH: 6,
  PASSWORD_MAX_LENGTH: 128,
  NAME_MAX_LENGTH: 100,
  EMAIL_MAX_LENGTH: 255,
  PHONE_MAX_LENGTH: 20,
  BCRYPT_SALT_ROUNDS: 12
} as const;

export const TOKEN_EXPIRY = {
  AUTH: '180d',
  EMAIL_CONFIRMATION: '24h',
  PASSWORD_RESET: '1h',
  ACCOUNT_DELETION: '24h'
} as const;

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503
} as const;

export const SUCCESS_MESSAGES = {
  REGISTRATION_SUCCESS: 'User registered successfully',
  LOGIN_SUCCESS: 'Login successful',
  LOGOUT_SUCCESS: 'Logout successful',
  PASSWORD_RESET_EMAIL_SENT: 'Password reset email sent',
  PASSWORD_RESET_SUCCESS: 'Password reset successful',
  EMAIL_CONFIRMED: 'Email confirmed successfully',
  CONFIRMATION_EMAIL_SENT: 'Confirmation email sent',
  ACCOUNT_DELETION_EMAIL_SENT: 'Account deletion confirmation email sent',
  ACCOUNT_DELETED: 'Account deleted successfully'
} as const;

export const RATE_LIMITS = {
  LOGIN_ATTEMPTS_PER_MINUTE: 5,
  REGISTRATION_ATTEMPTS_PER_HOUR: 3,
  PASSWORD_RESET_ATTEMPTS_PER_HOUR: 3,
  EMAIL_RESEND_ATTEMPTS_PER_HOUR: 5
} as const;

export const ENV_CONFIG = {
  DEVELOPMENT: 'development',
  PRODUCTION: 'production',
  TEST: 'test',
  DEFAULT_FRONTEND_URL_DEV: 'http://localhost:8101',
  DEFAULT_BACKEND_URL_DEV: 'http://localhost:3001'
} as const;

export type UserProvider = (typeof USER_PROVIDERS)[keyof typeof USER_PROVIDERS];
export type TokenType = (typeof TOKEN_TYPES)[keyof typeof TOKEN_TYPES];

export const PASSWORD_MIN_LENGTH = VALIDATION_RULES.PASSWORD_MIN_LENGTH;

export default {
  USER_PROVIDERS,
  TOKEN_TYPES,
  AUTH_ACTIONS,
  ACCOUNT_STATUS,
  ERROR_CODES,
  VALIDATION_RULES,
  TOKEN_EXPIRY,
  HTTP_STATUS,
  SUCCESS_MESSAGES,
  RATE_LIMITS,
  ENV_CONFIG
};
